name: Template workflow

on:
  push:
    branches:
      - main

    workflow_dispatch:

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List files
        run: ls -a
